In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

from sklearn.model_selection import KFold, StratifiedKFold, cross_val_score

import numpy as np


In [2]:
digits = load_digits()

In [42]:
len(digits.data[23: 90])

67

In [16]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [17]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9685185185185186

In [18]:
svc = SVC(kernel='linear')
svc.fit(X_train, y_train)
svc.score(X_test, y_test)

0.987037037037037

In [19]:
rf = RandomForestClassifier(n_estimators=20, criterion='entropy')
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9611111111111111

In [23]:
kf = KFold(n_splits=4)
kf

KFold(n_splits=4, random_state=None, shuffle=False)

In [24]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 5 6 7 8] [3 4]
[0 1 2 3 4 7 8] [5 6]
[0 1 2 3 4 5 6] [7 8]


In [33]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [27]:
folds = StratifiedKFold(n_splits=3)

In [43]:
scores_log = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
        digits.target[train_index], digits.target[test_index]
    
    scores_log.append(get_score(LogisticRegression(max_iter=1000), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [44]:
scores_log

[0.9333333333333333,
 0.9198218262806236,
 0.9487750556792873,
 0.9153674832962138]

In [45]:
scores_rf

[0.9133333333333333,
 0.9020044543429844,
 0.9576837416481069,
 0.9198218262806236]

In [46]:
scores_svm

[0.9644444444444444,
 0.9665924276169265,
 0.9821826280623608,
 0.9487750556792873]

In [49]:
cross_val_score(LogisticRegression(max_iter=1000), digits.data, digits.target)

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [50]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [51]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)

array([0.93888889, 0.89444444, 0.95543175, 0.96100279, 0.93871866])